### PR TITLE
Added note on decrypting fragmented videos

### PR DESCRIPTION
**Pull request by marekceglowski**

### CODE REVIEW

**Comment by tomer8007** [comment]
It also happens that you see multiple keys for videos that offer multiple resolutions/qualities.

**Comment by marekceglowski** [comment]
Oh I wasn't aware, good to know. Thanks!

**Comment by tomer8007** [comment]
Anyway I prefer not to detail about video decryption, the main purpose is here is getting the key.

**Comment by marekceglowski** [comment]
I understand, thanks

**Pull request closed without merging**
